GET http://localhost:7878/v1/api/teacher/test
Accept: application/json

###

###



###CREAR NUEVO PROFESOR

POST http://localhost:7878/v1/api/teacher
Content-Type: application/json

{
  "name": "Orlando Rivera",
  "subject": "Programación II"
}

###OBTENER TODOS LOS PROFESORES
GET http://localhost:7878/v1/api/teacher/all
Accept: application/json

###OBTENER TODOS LOS PROFESORES POR GATEWAY
GET http://192.168.1.14:8181/ms-teacher/v1/api/teacher/all
Accept: application/json

###ACTUALIZAR PROFESOR

PUT http://localhost:7878/v1/api/teacher/1
Content-Type: application/json

{
  "name": "Andrea Espinar",
  "subject": "Química Orgánica"
}


###CREAR NUEVO PROFESOR POR GATEWAY

POST http://192.168.1.14:8181/ms-teacher/v1/api/teacher
Content-Type: application/json
Origin: http://localhost:8080/teachers

{
  "name": "Andrea Espinar",
  "subject": "Química orgánica"
}

###CREAR NUEVO PROFESOR POR GATEWAY

POST http://localhost:8181/ms-teacher/v1/api/teacher
Content-Type: application/json
Origin: http://localhost:8080/teachers

{
  "name": "Andrea Espinar",
  "subject": "Química orgánica"
}
